apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-service1
  labels:
    app: helloworld-service1-selector
spec:
  replicas: 5
  selector:
    matchLabels:
      app: helloworld-service1-selector
  template:
    metadata:
      labels:
        app: "helloworld-service1-selector"
    spec:
      containers:
      - name: helloworld-service1
        image: dhiguerosr/kubernetes-demo:2.0.0
        ports:
        - containerPort: 3000